# Generated by Django 6.0.5 on 2026-05-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(unique=True)),
                ('sname', models.CharField(max_length=20)),
                ('smark', models.FloatField()),
                ('ssub', models.CharField(choices=[('MATH', 'MATH'), ('PHY', 'PHY'), ('CHE', 'CHE')], max_length=20)),
            ],
        ),
    ]
